### ISSUE TITLE
Duplication when querying the same column twice

### ISSUE THREAD

**Issue by juliuslipp** [sqlc-dev/sqlc-gen-python#43]
```sql
UPDATE api_keys
...
WHERE key = ? OR key = ?
```

->
```python
def update_api_key_last_used(self, *, key: Any, key: Any) -> None:
    self._conn.execute(sqlalchemy.text(UPDATE_API_KEY_LAST_USED), {"p1": key, "p2": key})
```

Config:
```yaml
version: '2'
plugins:
  - name: py
    wasm:
      url: https://downloads.sqlc.dev/plugin/sqlc-gen-python_1.2.0.wasm
      sha256: a6c5d174c407007c3717eea36ff0882744346e6ba991f92f71d6ab2895204c0e
sql:
  - engine: "sqlite"
    queries: "...."
    schema: "..."
    codegen:
      - out: "..."
        plugin: py
        options:
          emit_sync_querier: True
          emit_async_querier: True
          package: "database"

```
