### ISSUE TITLE
Add rename config in sqlc-gen-python

### ISSUE THREAD

**Issue by jeongukjae** [sqlc-dev/sqlc-gen-python#54]
How about adding rename config like this? https://docs.sqlc.dev/en/stable/howto/rename.html#renaming-fields

e.g.

```yaml
sql:
- engine: "..."
  queries:
    - "..."
  schema: "..."
  codegen:
  - out: ...
    plugin: py
    options:
      package: ...
      ...
    rename:
      ab_cd: "ABCd"
```
