### ISSUE TITLE
How to set default value to a dataclass field?

### ISSUE THREAD

**Issue by barenko** [sqlc-dev/sqlc-gen-python#58]
I want to set a None value in Optional dataclass fields. But I was unable to find how to do it in documentation. This is possible?

I have a table like:

```sql
create table t(
   id serial primary key, 
   name varchar not null, 
   description text null
)
```

running `sqlc generate` I got:

```python
@dataclasses.dataclass()
class T:
   id: int
   name: str
   description: Optional[str]
```

But what I really wants is a default None value in description, like:

```python
@dataclasses.dataclass()
class T:
   id: int
   name: str
   description: Optional[str] = None
```

I'm using sqlc v1.27.0 (by docker) and generating python code for postgres with the config:

```yaml
version: '2'
plugins:
- name: py
  wasm:
    url: https://downloads.sqlc.dev/plugin/sqlc-gen-python_1.2.0.wasm
    sha256: a6c5d174c407007c3717eea36ff0882744346e6ba991f92f71d6ab2895204c0e
sql:
- schema: "schema.sql"
  queries: "queries.sql"
  engine: postgresql
  codegen:
  - out: ./model
    plugin: py
    options:
      package: model
      emit_sync_querier: true
      emit_async_querier: true
      emit_empty_slices: true
```
