### ISSUE TITLE
files generated for SQLite are missing type annotations.

### ISSUE THREAD

**Issue by rfletchr** [sqlc-dev/sqlc-gen-python#64]
When generating python code with the engine set to sqlite the generated code has every property annotated with the Any type.

If I switch the engine to postgresql everything works as expected.

```yaml
version: '2'
plugins:
  - name: py
    wasm:
      url: https://downloads.sqlc.dev/plugin/sqlc-gen-python_1.2.0.wasm
      sha256: a6c5d174c407007c3717eea36ff0882744346e6ba991f92f71d6ab2895204c0e
sql:
  - schema: "schema.sql"
    queries: "query.sql"
    engine: sqlite
    codegen:
      - out: src/modeldb/db/schema
        plugin: py
        options:
          package: modeldb.db.schema
          emit_sync_querier: true
          emit_async_querier: true
          query_parameter_limit: 5
```

```sql
CREATE TABLE file
(
    id          INTEGER NOT NULL,
    name        text NOT NULL,
    path        text NOT NULL,
    hash        text NOT NULL,
    resource_id INTEGER NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (resource_id) REFERENCES resource (id)
);
```

```python
# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.27.0
import dataclasses
from typing import Any, Optional


@dataclasses.dataclass()
class File:
    id: Any
    name: Any
    path: Any
    hash: Any
    resource_id: Any
```

I realise sqlite plays fast and loose with types, but so does python. It'd be very beneficial to have this working.
