### ISSUE TITLE
[1]    87056 killed     sqlc compile

### ISSUE THREAD

**Issue by elvizlai** [sqlc-dev/sqlc-gen-python#80]
```
version: "2"
plugins:
  - name: py
    wasm:
      url: https://downloads.sqlc.dev/plugin/sqlc-gen-python_1.3.0.wasm
      sha256: fbedae96b5ecae2380a70fb5b925fd4bff58a6cfb1f3140375d098fbab7b3a3c
sql:
  - engine: "postgresql"
    schema: "sql/schema"
    queries: "sql/query"
    codegen:
      - out: dao/gen
        plugin: py
        options:
          package: dao.gen
          emit_sync_querier: true
          emit_async_querier: true

```

```
# sqlc version
v1.28.0

# codesign --verify --deep $(which sqlc)
# $?
0
```
