### ISSUE TITLE
Support for overriding types

### ISSUE THREAD

**Issue by oliverlambson** [sqlc-dev/sqlc-gen-python#82]
It would be really helpful to have the [override functionality available in the go version of sqlc](https://docs.sqlc.dev/en/stable/howto/overrides.html#overriding-types). In combination with the existing pydantic functionality, this would be very useful.

e.g., currently [`JSONB` columns are returned with `Any`](https://github.com/sqlc-dev/sqlc-gen-python/blob/53fa0b2e3d10c4201f7a5a344d00a560330da3bb/internal/postgresql_type.go#L22-L23) type. I would like to be able to override this behaviour on a per-column basis. This would be useful not only for "Any" types, but also for types where a different primitive is desired (e.g. a 3rd party UUID instead of the builtin, like the [go example](https://docs.sqlc.dev/en/stable/howto/overrides.html#overriding-types))

## Given this schema

```sql
-- schema.sql
CREATE TABLE some_table (
    id SERIAL NOT NULL,
    payload JSONB NOT NULL
);
```

## Current output of `sqlc generate` (uses Any for payload column)

```python
# db/models.py
# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
import pydantic
from typing import Any


class SomeTable(pydantic.BaseModel):
    id: int
    payload: Any
```

## Desired output (uses custom type for payload column)

```python
# db/models.py
# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.28.0
import pydantic
import my_lib.models


class SomeTable(pydantic.BaseModel):
    id: int
    payload: my_lib.models.Payload
```

## How it could work

I would imagine something in the config like:

```yaml
version: "2"
plugins:
  - name: py
    wasm:
      url: https://downloads.sqlc.dev/plugin/sqlc-gen-python_1.3.0.wasm
      sha256: fbedae96b5ecae2380a70fb5b925fd4bff58a6cfb1f3140375d098fbab7b3a3c
sql:
  - schema: "./schemq.sql"
    queries: "./query"
    engine: postgresql
    codegen:
      - out: ./packages/core/src/core/db
        plugin: py
        options:
          package: core.db
          emit_pydantic_models: true
          overrides:  # similar to the go overrides
            - column: "some_table.payload"
              py_import: "my_lib.models"
              py_type: "Payload"
```
